package com.mei.hermes.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.id
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.username
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.user_id
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.phone
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.birth
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.signature
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.location
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private Integer location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.create_time
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.update_time
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesmiser_user_info.status
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.id
     *
     * @return the value of lesmiser_user_info.id
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.id
     *
     * @param id the value for lesmiser_user_info.id
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.username
     *
     * @return the value of lesmiser_user_info.username
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.username
     *
     * @param username the value for lesmiser_user_info.username
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.user_id
     *
     * @return the value of lesmiser_user_info.user_id
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.user_id
     *
     * @param userId the value for lesmiser_user_info.user_id
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.phone
     *
     * @return the value of lesmiser_user_info.phone
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.phone
     *
     * @param phone the value for lesmiser_user_info.phone
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.birth
     *
     * @return the value of lesmiser_user_info.birth
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.birth
     *
     * @param birth the value for lesmiser_user_info.birth
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.signature
     *
     * @return the value of lesmiser_user_info.signature
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.signature
     *
     * @param signature the value for lesmiser_user_info.signature
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.location
     *
     * @return the value of lesmiser_user_info.location
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.location
     *
     * @param location the value for lesmiser_user_info.location
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.create_time
     *
     * @return the value of lesmiser_user_info.create_time
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.create_time
     *
     * @param createTime the value for lesmiser_user_info.create_time
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.update_time
     *
     * @return the value of lesmiser_user_info.update_time
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.update_time
     *
     * @param updateTime the value for lesmiser_user_info.update_time
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesmiser_user_info.status
     *
     * @return the value of lesmiser_user_info.status
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesmiser_user_info.status
     *
     * @param status the value for lesmiser_user_info.status
     *
     * @mbg.generated Mon Apr 13 21:36:27 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}